/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-01-15 05:50:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bottom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<div class=\"footer_content\">\n");
      out.write("  <div class=\"footer_content_page\">\n");
      out.write("    <ul class=\"footer_content_page_list\">\n");
      out.write("      <li class=\"footer_tit\">고객센터</li>\n");
      out.write("      <li>\n");
      out.write("        <a href=\"faq.jsp\" class=\"link\">FAQ</a>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <a href=\"agreement.jsp\" class=\"link\">이용약관</a>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <a href=\"privacy.jsp\" class=\"link\">개인정보 처리방침</a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("    <ul class=\"footer_content_page_list\">\n");
      out.write("      <li class=\"footer_tit\">회사소개</li>\n");
      out.write("      <li>\n");
      out.write("        <a href=\"aboutus.jsp\" class=\"link\">About us</a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("    <ul class=\"footer_content_page_list\">\n");
      out.write("      <li class=\"footer_tit\">파트너쉽</li>\n");
      out.write("      <li>\n");
      out.write("        <a href=\"contactus.jsp\" class=\"link\">Contact us</a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"footer_content_payment\">\n");
      out.write("    <p class=\"footer_tit\">결제수단</p>\n");
      out.write("    <img src=\"../images/main/pay_icon01.svg\" alt=\"\" class=\"icon\">\n");
      out.write("    <img src=\"../images/main/pay_icon02.svg\" alt=\"\" class=\"icon\">\n");
      out.write("    <img src=\"../images/main/pay_icon03.svg\" alt=\"\" class=\"icon\">\n");
      out.write("  </div>\n");
      out.write("  <div class=\"footer_content_sns\">\n");
      out.write("    <p class=\"footer_tit\">Follow us</p>\n");
      out.write("    <a href=\"https://www.facebook.com/waugkorea\" target=\"_blank\" class=\"link\">\n");
      out.write("      <img src=\"../images/main/sns_facebook.svg\" alt=\"\" class=\"icon\">\n");
      out.write("    </a>\n");
      out.write("    <a href=\"https://www.instagram.com/waug_official/\" target=\"_blank\" class=\"link\">\n");
      out.write("      <img src=\"../images/main/sns_instagram.svg\" alt=\"\" class=\"icon\">\n");
      out.write("    </a>\n");
      out.write("    <a href=\"https://post.naver.com/ravetrip\" target=\"_blank\" class=\"link\">\n");
      out.write("      <img src=\"../images/main/sns_naverpost.svg\" alt=\"\" class=\"icon\">\n");
      out.write("    </a>\n");
      out.write("    <a href=\"https://blog.waug.com/\" target=\"_blank\" class=\"link\">\n");
      out.write("      <img src=\"../images/main/sns_blog.svg\" alt=\"\" class=\"icon\">\n");
      out.write("    </a>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<div class=\"footer_address\">\n");
      out.write("  <address>\n");
      out.write("    Republic of Korea : 2F, 36, Gyeonghuigung-gil, Jongno-gu, Seoul, Republic of Korea<br>\n");
      out.write("    Customer Support Center : +82 ) 070-4353-5959<br>\n");
      out.write("    Weekday AM 10:00 - PM 06:00 (GMT+9)<br>\n");
      out.write("    Weekends & Public Holidays AM 10:00 - PM 05:00 (GMT+9)<br>\n");
      out.write("    help@waug.com<br>\n");
      out.write("    Singapore : 10 Anson Road, #34-10 International Plaza, Singapore<br>\n");
      out.write("    WAGU Inc. is a sales broker, we are not responsible for any product information and transactions.\n");
      out.write("  </address>\n");
      out.write("  <address>\n");
      out.write("    <span>WAGU Team.<br>\n");
      out.write("    Oh, Dahyun | Jeong, Yukyung | Jo, Yeojeong | Kim, Daeun</span> <br>\n");
      out.write("    Business Registration Number, 113-86-94943<br>\n");
      out.write("    Mail-order Distributor Registration Number, 2020-서울종로-1199<br>\n");
      out.write("    South Korea Travel Agent Licence : 2020 - 000029<br>\n");
      out.write("    Singapore Travel Agent Licence : 03226<br>\n");
      out.write("    © 2022 WAGU Project. All Rights Reserved.\n");
      out.write("  </address>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
