/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-01-15 11:28:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class korailReservation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>WAGU - 액티비티, 와서 구경해~</title>\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\"  href=\"images/favicon.png\"/>\r\n");
      out.write("    <link rel=\"shortcut icon\" sizes=\"72x72\" href=\"images/favicon.png\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../fonts/SUIT/SUIT.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/korailReservation.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/df844253b1.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- <script src=\"../js/subItems.js\"></script> -->\r\n");
      out.write("    <script>\r\n");
      out.write("      $(function(){\r\n");
      out.write("        $('.header').load('top.html');\r\n");
      out.write("        var script = document.createElement(\"script\");\r\n");
      out.write("            script.type = \"text/javascript\";\r\n");
      out.write("            script.src = \"../js/common.js\";\r\n");
      out.write("            $(\"head\").append(script);\r\n");
      out.write("        $('.next_button').click(function(){\r\n");
      out.write("        	location.href=\"korailPayment.jsp\";\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("      })\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("      <header class=\"header sub\">\r\n");
      out.write("        <!-- top.html -->\r\n");
      out.write("      </header>\r\n");
      out.write("\r\n");
      out.write("      <main class=\"main sub\">\r\n");
      out.write("        <div class=\"order_korail_info\">\r\n");
      out.write("          <div class=\"korail_reservation_info_wrapper\">\r\n");
      out.write("            <div class=\"korail_reservation_info_title\">선택된 승차권 정보</div>\r\n");
      out.write("            <div class=\"korail_reservation_info_content\">\r\n");
      out.write("              <div class=\"railWay\">가는편</div>\r\n");
      out.write("              <div class=\"top_info\">\r\n");
      out.write("                <div class=\"time_form\">\r\n");
      out.write("                  <div class=\"station\">대전</div>\r\n");
      out.write("                  <div class=\"time\">05:28</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"timetaken_form\">\r\n");
      out.write("                  <div class=\"train\">무궁화 1316</div>\r\n");
      out.write("                  <p class = \"timetaken\"><span>2시간 10분</span></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"time_form\">\r\n");
      out.write("                  <div class=\"station\">서울</div>\r\n");
      out.write("                  <div class=\"time\">07:38</div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"m_info\">\r\n");
      out.write("                <div class=\"form\">\r\n");
      out.write("                  <div class=\"title\">출발일</div>\r\n");
      out.write("                  <div class=\"content\">2023년 01월 16일(월)</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form\">\r\n");
      out.write("                  <div class=\"title\">인원</div>\r\n");
      out.write("                  <div class=\"content\">성인 1 , 어린이 1</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form\">\r\n");
      out.write("                  <div class=\"title\">좌석</div>\r\n");
      out.write("                  <div class=\"content\">1호차 1A,1B</div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"price_info\">\r\n");
      out.write("                <div class=\"price\">₩ 16,200</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"korail_reservation_info_content\" >\r\n");
      out.write("              <div class=\"railWay\">오는편</div>\r\n");
      out.write("              <div class=\"top_info\">\r\n");
      out.write("                <div class=\"time_form\">\r\n");
      out.write("                  <div class=\"station\">서울</div>\r\n");
      out.write("                  <div class=\"time\">05:15</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"timetaken_form\">\r\n");
      out.write("                  <div class=\"train\">KTX1</div>\r\n");
      out.write("                  <p class = \"timetaken\"><span>0시간 59분</span></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"time_form\">\r\n");
      out.write("                  <div class=\"station\">대전</div>\r\n");
      out.write("                  <div class=\"time\">06:14</div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"m_info\">\r\n");
      out.write("                <div class=\"form\">\r\n");
      out.write("                  <div class=\"title\">출발일</div>\r\n");
      out.write("                  <div class=\"content\">2023년 01월 17일(화)</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form\">\r\n");
      out.write("                  <div class=\"title\">인원</div>\r\n");
      out.write("                  <div class=\"content\">성인 1 , 어린이 1</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form\">\r\n");
      out.write("                  <div class=\"title\">좌석</div>\r\n");
      out.write("                  <div class=\"content\">1호차 1A,1B</div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"price_info\">\r\n");
      out.write("                <div class=\"price\">₩ 35,550</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"passenger_info_wrapper\">\r\n");
      out.write("            <div class=\"passenger_info_title\">열차 탑승객 정보</div>\r\n");
      out.write("            <div class=\"sub_title\">※ 입력하신 정보는 기차 탑승 및 탑승권 확인 시 활용됩니다.</div>\r\n");
      out.write("            <div class=\"name_info\">\r\n");
      out.write("              <div class=\"content_title\">이름(대표 탑승자 이름)</div>\r\n");
      out.write("              <input type=\"text\" placeholder=\"이름을 입력해주세요\" class=\"name_input\" value=\"김다은\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"birth_info\">\r\n");
      out.write("              <div class=\"content_title\">생년월일</div>\r\n");
      out.write("              <input type=\"text\" placeholder=\"생년월일을 입력해주세요\" class=\"birth_input\" value=\"19971222\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"phone_info\">\r\n");
      out.write("              <div class=\"content_title\">휴대전화번호</div>\r\n");
      out.write("              <input type=\"text\" placeholder=\"휴대전화번호를 입력해주세요\" class=\"phone_input\" value=\"01012345678\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"email_info\">\r\n");
      out.write("              <div class=\"content_title\">이메일</div>\r\n");
      out.write("              <input type=\"text\" placeholder=\"이메일을 입력해주세요\" class=\"email_input\" value=\"ekdms12@naver.com\">\r\n");
      out.write("            </div>\r\n");
      out.write("          <!--   <a href=\"#n\" class=\"my_info\">내 정보 불러오기</a> -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <button class=\"next_button\">\r\n");
      out.write("            <div class=\"next\">다음</div>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </main>\r\n");
      out.write("      <footer class=\"footer\">\r\n");
      out.write("        <!-- bottom.html -->\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
