/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-01-15 09:58:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class korailPayment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>WAGU - 액티비티, 와서 구경해~</title>\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\"  href=\"images/favicon.png\"/>\r\n");
      out.write("    <link rel=\"shortcut icon\" sizes=\"72x72\" href=\"images/favicon.png\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../fonts/SUIT/SUIT.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/korailPayment.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css\">\r\n");
      out.write("    <script src=\"../js/common.js\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/df844253b1.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- <script src=\"../js/subItems.js\"></script> -->\r\n");
      out.write("    <script>\r\n");
      out.write("      $(function(){\r\n");
      out.write("        $('.payment_next_btn').click(function(){\r\n");
      out.write("        	location.href=\"korailPaymentCheck.jsp\";\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("      })\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"../js/korailPayment.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("      <header class=\"header sub\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("      </header>\r\n");
      out.write("      <div class=\"privacy_popup\">\r\n");
      out.write("        <div class=\"dim\"></div>\r\n");
      out.write("        <div class=\"privacy_popup_content\">\r\n");
      out.write("          <div class=\"privacy_popup_top\">\r\n");
      out.write("            <div class=\"privacy_popup_title\">개인정보 제 3자 제공 동의</div>\r\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" fill=\"currentColor\" class=\"close_button agree\" viewBox=\"0 0 16 16\">\r\n");
      out.write("              <path d=\"M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"privacy_popup_body\">\r\n");
      out.write("            <div class=\"policy\">\r\n");
      out.write("              <strong>회원의 개인정보는 당사의 개인정보처리 방침에 따라 안전하게 보호됩니다.</strong>\r\n");
      out.write("              <p>\"WAUG Inc.\"은 이용자들의 개인정보를 \"개인정보 처리방침의 개인정보의 수집 및 이용목적\"에서 고지한 범위내에서 사용하며, 이용자의 사전 동의 없이는 동 범위를 초과하여 이용하거나 원칙적으로 이용자의 개인정보를 외부에 공개하지않습니다</p>\r\n");
      out.write("              <p>\"WAUG Inc.\"이 제공하는 서비스를 통하여 주문 및 결제가 이루어진 경우 구매자 확인등 거래이행을 위해 관련된 정보를 필요한 범위내에서 거래 업체에게 제공합니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"summary\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <h2>I 제공 목적</h2>\r\n");
      out.write("                <li>구매자 예약 확인</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"summary\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <h2>I 제공 정보</h2>\r\n");
      out.write("                <li>성명</li>\r\n");
      out.write("                <li>휴대전화번호</li>\r\n");
      out.write("                <li>주소</li>\r\n");
      out.write("                <li>이메일</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"summary\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <h2>I 보유 및 이용 기간</h2>\r\n");
      out.write("                <li>상품 제공 완료 후 3개월</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-------------------------------------------------------------------------->\r\n");
      out.write("      <main class=\"main sub\">\r\n");
      out.write("        <div class=\"payment_page_box\">\r\n");
      out.write("          <div class=\"left\">\r\n");
      out.write("            <div class=\"reservation_payment_info\">\r\n");
      out.write("              <div class=\"reservation_payment_header\">예약정보</div>\r\n");
      out.write("              <div class=\"reservation_payment_box\">\r\n");
      out.write("                <div class = \"reservation_payment_content\">\r\n");
      out.write("                  <div class=\"payment_info_title\">\r\n");
      out.write("                    <img src=\"../images/korail/station_icon.svg\" alt=\"기차 아이콘\">\r\n");
      out.write("                    <p>열차</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"payment_info_body\">\r\n");
      out.write("                    <div class=\"korail_reservation_info_content\" >\r\n");
      out.write("                      <div class=\"railWay\">가는편</div>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"top_info\">\r\n");
      out.write("                          <div class=\"time_form\">\r\n");
      out.write("                            <div class=\"station\">대전</div>\r\n");
      out.write("                            <div class=\"time\">05:28</div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"timetaken_form\">\r\n");
      out.write("                            <div class=\"train\">무궁화 1316</div>\r\n");
      out.write("                            <p class = \"timetaken\"><span>2시간 10분</span></p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"time_form\">\r\n");
      out.write("                            <div class=\"station\">서울</div>\r\n");
      out.write("                            <div class=\"time\">07:38</div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"m_info\">\r\n");
      out.write("                          <div class=\"form\">\r\n");
      out.write("                            <div class=\"title\">출발일</div>\r\n");
      out.write("                            <div class=\"content\">2023년 11월 16일(월)</div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form\">\r\n");
      out.write("                            <div class=\"title\">인원</div>\r\n");
      out.write("                            <div class=\"content\">성인 1 , 어린이 1</div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form\">\r\n");
      out.write("                            <div class=\"title\">좌석</div>\r\n");
      out.write("                            <div class=\"content\">1호차 1,2</div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"price_info\">\r\n");
      out.write("                          <div class=\"price\">₩ 16,200</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"korail_reservation_info_content\" >\r\n");
      out.write("                      <div class=\"railWay\">오는편</div>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"top_info\">\r\n");
      out.write("                          <div class=\"time_form\">\r\n");
      out.write("                            <div class=\"station\">서울</div>\r\n");
      out.write("                            <div class=\"time\">05:15</div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"timetaken_form\">\r\n");
      out.write("                            <div class=\"train\">KTX 1</div>\r\n");
      out.write("                            <p class = \"timetaken\"><span>0시간 59분</span></p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"time_form\">\r\n");
      out.write("                            <div class=\"station\">대전</div>\r\n");
      out.write("                            <div class=\"time\">06:14</div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"m_info\">\r\n");
      out.write("                          <div class=\"form\">\r\n");
      out.write("                            <div class=\"title\">출발일</div>\r\n");
      out.write("                            <div class=\"content\">2023년 01월 17일(화)</div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form\">\r\n");
      out.write("                            <div class=\"title\">인원</div>\r\n");
      out.write("                            <div class=\"content\">성인 1 , 어린이 1</div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form\">\r\n");
      out.write("                            <div class=\"title\">좌석</div>\r\n");
      out.write("                            <div class=\"content\">1호차 1A,1B</div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"price_info\">\r\n");
      out.write("                          <div class=\"price\">₩ 35,550</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"reservation_payment_footer\">\r\n");
      out.write("                <div class=\"sum_price_title\">총 금액</div>\r\n");
      out.write("                <div class=\"sum_price\">₩ 51,750</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"right\">\r\n");
      out.write("            <div class=\"payment_way\">		\r\n");
      out.write("              <div class=\"infocommon_title\">결제수단</div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"selected_payment_way_list_card\">\r\n");
      out.write("                <div class=\"selected_wrapper\">\r\n");
      out.write("                  <div class=\"title_section card\">\r\n");
      out.write("                    <img class=\"payment_logo card\" src=\"../images/common/imgpaymentcardlogoblack.svg\" alt=\"card logo\">\r\n");
      out.write("                    <div class=\"payment_list_title\">카드</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"selecting_option\"> \r\n");
      out.write("                    <div class=\"selecting_option_title\">카드종류</div>\r\n");
      out.write("                    <div class=\"card_type\">\r\n");
      out.write("                      <div class=\"card_option active\">\r\n");
      out.write("                        <img class=\"card_image active\" src=\"../images/common/imgcardlogohyundai.svg\" alt=\"hyundai\">\r\n");
      out.write("                        <div class=\"card_name\">현대카드</div>	\r\n");
      out.write("                      </div>	\r\n");
      out.write("                      <div class=\"card_option\">\r\n");
      out.write("                        <img class=\"card_image\" src=\"../images/common/imgcardlogosamsung.svg\" alt=\"samsung\">\r\n");
      out.write("                        <div class=\"card_name\">삼성카드</div>	\r\n");
      out.write("                      </div>	\r\n");
      out.write("                      <div class=\"card_option\">\r\n");
      out.write("                        <img class=\"card_image\" src=\"../images/common/imgcardlogobc.svg\" alt=\"bc\">\r\n");
      out.write("                        <div class=\"card_name\">비씨카드</div>	\r\n");
      out.write("                      </div>	\r\n");
      out.write("                      <div class=\"card_option\">\r\n");
      out.write("                        <img class=\"card_image\" src=\"../images/common/imgcardlogokb.svg\" alt=\"kb\">\r\n");
      out.write("                        <div class=\"card_name\">국민카드</div>	\r\n");
      out.write("                      </div>	\r\n");
      out.write("                      <div class=\"card_option\">\r\n");
      out.write("                        <img class=\"card_image\" src=\"../images/common/imgcardlogohana.svg\" alt=\"hana\">\r\n");
      out.write("                        <div class=\"card_name\">하나카드</div>	\r\n");
      out.write("                      </div>	\r\n");
      out.write("                      <div class=\"card_option\">\r\n");
      out.write("                        <img class=\"card_image\" src=\"../images/common/imgcardlogolotte.svg\" alt=\"lotte\">\r\n");
      out.write("                        <div class=\"card_name\">롯데카드</div>	\r\n");
      out.write("                      </div>	\r\n");
      out.write("                      <div class=\"card_option\">\r\n");
      out.write("                        <img class=\"card_image\" src=\"../images/common/imgcardlogonh.svg\" alt=\"nh\">\r\n");
      out.write("                        <div class=\"card_name\">농협카드</div>	\r\n");
      out.write("                      </div>	\r\n");
      out.write("                      <div class=\"card_option\">\r\n");
      out.write("                        <img class=\"card_image\" src=\"../images/common/imgcardlogosh.svg\" alt=\"sh\">\r\n");
      out.write("                        <div class=\"card_name\">신한카드</div>	\r\n");
      out.write("                      </div>	\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"other_card_section\">\r\n");
      out.write("                      <div class=\"other_card_wrapper\">\r\n");
      out.write("                        <button class=\"other_card\">다른카드 선택</button>\r\n");
      out.write("                        <ul class=\"other_card_listbox\" id=\"other_card_listbox\">\r\n");
      out.write("                          <!-- <li><button class=\"cardlist active\">다른카드 선택</button></li> -->\r\n");
      out.write("                          <li><button class=\"cardlist\">카카오뱅크</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">하나(외환)카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">KDB 산업체크카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">우리카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">수협카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">전북카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">씨티카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">우체국체크카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">MG 새마을금고체크카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">저축은행체크카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">제주카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">광주카드</button></li>\r\n");
      out.write("                          <li><button class=\"cardlist\">신협체크카드</button></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"selecting_option_title\">할부 선택</div>\r\n");
      out.write("                    <div class=\"monthly_payment_section\">\r\n");
      out.write("                      <button class=\"monthly_payment month\"></button>\r\n");
      out.write("                      <ul class=\"selecting_payment month\" id=\"selecting_payment\">\r\n");
      out.write("                        <li><button  class=\"monthlylist active\">일시불</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">2개월</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">3개월</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">4개월</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">5개월</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">6개월</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">7개월</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">8개월</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">9개월</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">10개월</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">11개월</button></li>\r\n");
      out.write("                        <li><button  class=\"monthlylist\">12개월</button></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"installment_notice\">무이자 할부 안내 보기 ></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              \r\n");
      out.write("              </div>\r\n");
      out.write("              <div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"selected_payment_way_list_bank\">\r\n");
      out.write("                  <div class=\"bank_wrapper\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\" class=\"payment_logo\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                      <path fill-rule=\"evenodd\" d=\"M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z\"/>\r\n");
      out.write("                      <path d=\"M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z\"/>\r\n");
      out.write("                      <path d=\"M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z\"/>\r\n");
      out.write("                      <path d=\"M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <div class=\"payment_list_title\">무통장 입금</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bank_payment_section\">\r\n");
      out.write("                      <div class=\"bank_payment_wrapper\">\r\n");
      out.write("                      <button class=\"monthly_payment bank\">입금은행 선택</button>\r\n");
      out.write("                          <ul class=\"selecting_payment bank\" id=\"selecting_payment\">\r\n");
      out.write("                            <li><button  class=\"paymentlist\">국민은행</button></li>\r\n");
      out.write("                            <li><button  class=\"paymentlist\">하나은행</button></li>\r\n");
      out.write("                            <li><button  class=\"paymentlist\">신한은행</button></li>\r\n");
      out.write("                            <li><button  class=\"paymentlist\">우리은행</button></li>\r\n");
      out.write("                            <li><button  class=\"paymentlist\">농협은행</button></li>\r\n");
      out.write("                            <li><button  class=\"paymentlist\">IBK 기업은행</button></li>\r\n");
      out.write("                            <li><button  class=\"paymentlist\">SC 제일은행</button></li>\r\n");
      out.write("                            <li><button  class=\"paymentlist\">신협은행</button></li>\r\n");
      out.write("                            <li><button  class=\"paymentlist\">MG 새마을금고</button></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                    </div>	\r\n");
      out.write("                  </div>	\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"agree_box\">\r\n");
      out.write("              <div class=\"agree_title\">약관동의</div>\r\n");
      out.write("              <form class=\"agree_content\">\r\n");
      out.write("                <label class=\"all_agree\"><input class=\"allAgree\" type=\"checkbox\" name=\"agree\" value=\"all\">전체 동의</label>\r\n");
      out.write("              </form>\r\n");
      out.write("              <form class=\"agree_content_detail\">\r\n");
      out.write("                <label class=\"agree\">\r\n");
      out.write("                  <input class =\"agreeDetail\" type=\"checkbox\" name=\"agree\" value=\"agree\">개인정보 제3자 제공 동의\r\n");
      out.write("                  <button class=\"professional_view\">[전문보기]</button>\r\n");
      out.write("                </label>\r\n");
      out.write("                <label class=\"agree\">\r\n");
      out.write("                  <input class =\"agreeDetail\" type=\"checkbox\" name=\"agree\" value=\"agree\">코레일 예약 취소 및 환불 내용 동의\r\n");
      out.write("                </label>\r\n");
      out.write("              </form>\r\n");
      out.write("    \r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"payment_info\">\r\n");
      out.write("              <div class=\"payment_info_header\">결제 정보</div>\r\n");
      out.write("              <div class=\"payment_info_body\">\r\n");
      out.write("                <div class=\"payment_info_subtitle\">총금액<span>₩ 51,750</span></div>\r\n");
      out.write("                <div class=\"payment_info_subtitle\">쿠폰<span>-₩ 0</span></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"payment_info_footer\">\r\n");
      out.write("                <div class=\"total_price\">총 결제 금액 <span>₩ 51,750</span></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"last_check\">\r\n");
      out.write("                ※ (주)와그는 통신판매중개자로서 통신판매의 당사자가 아니며, 상품의 예약, 이용 및 환불 등과 관련한 의무와 책임은 각 판매자에게 있습니다.\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"payment_next_btn\">\r\n");
      out.write("                <input type=\"submit\" value=\"결제하기\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </main>\r\n");
      out.write("      <footer class=\"footer\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bottom.jsp", out, false);
      out.write("\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
