/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-01-15 10:02:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class korailPaymentCheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>WAGU - 액티비티, 와서 구경해~</title>\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\"  href=\"images/favicon.png\"/>\r\n");
      out.write("    <link rel=\"shortcut icon\" sizes=\"72x72\" href=\"images/favicon.png\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../fonts/SUIT/SUIT.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/korailPaymentCheck.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/df844253b1.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- <script src=\"../js/subItems.js\"></script> -->\r\n");
      out.write("    <script>\r\n");
      out.write("      $(function(){\r\n");
      out.write("     	$('.basket_btn').click(function(){\r\n");
      out.write("     		location.href=\"mypageKorail.jsp\";\r\n");
      out.write("     	})\r\n");
      out.write("      })\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("      <header class=\"header sub\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("      </header>\r\n");
      out.write("\r\n");
      out.write("      <main class=\"main sub\">\r\n");
      out.write("        <div class=\"waiting_payment\">\r\n");
      out.write("          <div class=\"top\">\r\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"28\" height=\"28\" fill=\"currentColor\" class=\"bi bi-check-circle-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("              <path d=\"M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            <span>결제 대기중입니다.</span>\r\n");
      out.write("            <span>(금일 자정까지 입금이 완료되지 않을 경우, 자동 취소됩니다.)</span>\r\n");
      out.write("            <button class=\"basket_btn\">구매내역</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"center\">\r\n");
      out.write("            <div class=\"title\">예약 정보</div>\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("              <div class=\"content_detail\">\r\n");
      out.write("                <div class=\"korail_logo\">\r\n");
      out.write("                  <img src=\"../images/korail/station_icon.svg\" alt=\"코레일\">\r\n");
      out.write("                  <span>코레일</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"reservation_info\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("                  <div class=\"train_info train\">\r\n");
      out.write("                    <div class=\"start\">\r\n");
      out.write("                      <p class=\"station\">대전</p>\r\n");
      out.write("                      <p class=\"time\">05:28</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-arrow-right-short\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                      <path fill-rule=\"evenodd\" d=\"M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <div class=\"arrive\" style=\"margin-right: 20px;\">\r\n");
      out.write("                      <p class=\"station\">서울</p>\r\n");
      out.write("                      <p class=\"time\">07:38</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"train_info\">\r\n");
      out.write("                    <p class=\"tit\">열차</p>\r\n");
      out.write("                    <p class=\"text\">무궁화 1316</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"train_info\">\r\n");
      out.write("                    <p class=\"tit\">출발일</p>\r\n");
      out.write("                    <p class=\"text\">2023년 01월 16일(월)</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"train_info\">\r\n");
      out.write("                    <p class=\"tit\">인원</p>\r\n");
      out.write("                    <p class=\"text\">성인1,어린이1</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"train_info\">\r\n");
      out.write("                    <p class=\"tit\">좌석</p>\r\n");
      out.write("                    <p class=\"text\">1호차 1,2</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                 <div class=\"reservation_info\">\r\n");
      out.write("                  <div class=\"train_info train\">\r\n");
      out.write("                    <div class=\"start\">\r\n");
      out.write("                      <p class=\"station\">서울</p>\r\n");
      out.write("                      <p class=\"time\">05:15</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-arrow-right-short\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                      <path fill-rule=\"evenodd\" d=\"M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <div class=\"arrive\" style=\"margin-right: 20px;\">\r\n");
      out.write("                      <p class=\"station\">대전</p>\r\n");
      out.write("                      <p class=\"time\">06:14</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"train_info\">\r\n");
      out.write("                    <p class=\"tit\">열차</p>\r\n");
      out.write("                    <p class=\"text\">KTX 1</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"train_info\">\r\n");
      out.write("                    <p class=\"tit\">출발일</p>\r\n");
      out.write("                    <p class=\"text\">2023년 01월 17일(화)</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"train_info\">\r\n");
      out.write("                    <p class=\"tit\">인원</p>\r\n");
      out.write("                    <p class=\"text\">성인1,어린이1</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"train_info\">\r\n");
      out.write("                    <p class=\"tit\">좌석</p>\r\n");
      out.write("                    <p class=\"text\">1호차 1A,1B</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"bottom\">\r\n");
      out.write("            <div class=\"title\">결제 정보</div>\r\n");
      out.write("            <div class=\"payment_info\">\r\n");
      out.write("              <div class=\"left\">\r\n");
      out.write("                <div class=\"payment\">\r\n");
      out.write("                  <span style=\"color:#c0c0c0\">결제수단</span>\r\n");
      out.write("                  <span>무통장 입금</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"total_price\">\r\n");
      out.write("                  <span style=\"color:#c0c0c0\">총 금액</span>\r\n");
      out.write("                  <span>₩ 51,750</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"right\">\r\n");
      out.write("                <div class=\"total_korail_price\" >\r\n");
      out.write("                  <span>총 결제 금액</span>\r\n");
      out.write("                  <span style=\"color:#d91c84;\">₩ 51,750</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </main>\r\n");
      out.write("      <footer class=\"footer\">\r\n");
      out.write("         ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bottom.jsp", out, false);
      out.write("\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
