/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-01-15 10:02:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypageKorail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>WAGU - 마이페이지</title>\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\"  href=\"../images/favicon.png\"/>\n");
      out.write("    <link rel=\"shortcut icon\" sizes=\"72x72\" href=\"../images/favicon.png\" type=\"image/x-icon\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../fonts/SUIT/SUIT.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/reset.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/common.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/mypage.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css\">\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js\"></script>\n");
      out.write("    <script src=\"https://kit.fontawesome.com/df844253b1.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"../js/jquery-3.6.3.min.js\"></script>\n");
      out.write("    <script src=\"../js/common.js\" defer></script>\n");
      out.write("    <script src=\"../js/mypage.js\"></script>\n");
      out.write("    <style>\n");
      out.write("      @media screen and (max-width: 768px) {\n");
      out.write("        .header_user_info > i {\n");
      out.write("          display: none;\n");
      out.write("        }\n");
      out.write("      }\n");
      out.write("    </style>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <div class=\"wrap\">\n");
      out.write("      <header class=\"header sub\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\n");
      out.write("      </header>\n");
      out.write("      <main class=\"main sub\">\n");
      out.write("        <h2 class=\"mypage_tit\">내 정보</h2>\n");
      out.write("        <section class=\"mypage_left\">\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mypageLeft.jsp", out, false);
      out.write("\n");
      out.write("        </section>\n");
      out.write("        <section class=\"mypage_content hotel\">\n");
      out.write("          <h3 class=\"mypage_content_tit\">열차 승차권</h3>\n");
      out.write("          <article class=\"mypage_content_korail\">\n");
      out.write("            <ul class=\"mypage_content_korail_list\">\n");
      out.write("              <li>\n");
      out.write("                <a href=\"mypageKorailDetail.jsp\" class=\"link\">\n");
      out.write("                  <div class=\"mypage_content_korail_reservation\">\n");
      out.write("                    <p class=\"korail_reservation_status status_cancel\">취소완료</p>\n");
      out.write("                    <p class=\"korail_reservation_number\">예약번호 <span>20220926138142</span></p>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"mypage_content_korail_info\">\n");
      out.write("                    <div class=\"info_train train\">\n");
      out.write("                      <div class=\"info_train_station\">\n");
      out.write("                        <p class=\"station\">용산</p>\n");
      out.write("                        <p class=\"time\">05:10</p>\n");
      out.write("                      </div>\n");
      out.write("                      <i class=\"fa-solid fa-arrow-right\"></i>\n");
      out.write("                      <div class=\"info_train_station\">\n");
      out.write("                        <p class=\"station\">광명</p>\n");
      out.write("                        <p class=\"time\">05:24</p>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">열차</p>\n");
      out.write("                      <p class=\"txt\">KTX</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">출발일</p>\n");
      out.write("                      <p class=\"txt\">2022년 12월 11일 (일)</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">인원</p>\n");
      out.write("                      <p class=\"txt\">성인1</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">좌석</p>\n");
      out.write("                      <p class=\"txt\">15호차 2B</p>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <a href=\"mypageKorailDetail.html\" class=\"link\">\n");
      out.write("                  <div class=\"mypage_content_korail_reservation\">\n");
      out.write("                    <p class=\"korail_reservation_status status_available\">탑승예정</p>\n");
      out.write("                    <p class=\"korail_reservation_number\">예약번호 <span>20220926138142</span></p>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"mypage_content_korail_info\">\n");
      out.write("                    <div class=\"info_train train\">\n");
      out.write("                      <div class=\"info_train_station\">\n");
      out.write("                        <p class=\"station\">용산</p>\n");
      out.write("                        <p class=\"time\">05:10</p>\n");
      out.write("                      </div>\n");
      out.write("                      <i class=\"fa-solid fa-arrow-right\"></i>\n");
      out.write("                      <div class=\"info_train_station\">\n");
      out.write("                        <p class=\"station\">광명</p>\n");
      out.write("                        <p class=\"time\">05:24</p>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">열차</p>\n");
      out.write("                      <p class=\"txt\">KTX</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">출발일</p>\n");
      out.write("                      <p class=\"txt\">2022년 12월 11일 (일)</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">인원</p>\n");
      out.write("                      <p class=\"txt\">성인1</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">좌석</p>\n");
      out.write("                      <p class=\"txt\">15호차 2B</p>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <a href=\"mypageKorailDetail.html\" class=\"link\">\n");
      out.write("                  <div class=\"mypage_content_korail_reservation\">\n");
      out.write("                    <p class=\"korail_reservation_status status_complete\">탑승완료</p>\n");
      out.write("                    <p class=\"korail_reservation_number\">예약번호 <span>20220926138142</span></p>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"mypage_content_korail_info\">\n");
      out.write("                    <div class=\"info_train train\">\n");
      out.write("                      <div class=\"info_train_station\">\n");
      out.write("                        <p class=\"station\">용산</p>\n");
      out.write("                        <p class=\"time\">05:10</p>\n");
      out.write("                      </div>\n");
      out.write("                      <i class=\"fa-solid fa-arrow-right\"></i>\n");
      out.write("                      <div class=\"info_train_station\">\n");
      out.write("                        <p class=\"station\">광명</p>\n");
      out.write("                        <p class=\"time\">05:24</p>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">열차</p>\n");
      out.write("                      <p class=\"txt\">KTX</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">출발일</p>\n");
      out.write("                      <p class=\"txt\">2022년 12월 11일 (일)</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">인원</p>\n");
      out.write("                      <p class=\"txt\">성인1</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">좌석</p>\n");
      out.write("                      <p class=\"txt\">15호차 2B</p>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <a href=\"mypageKorailDetail.html\" class=\"link\">\n");
      out.write("                  <div class=\"mypage_content_korail_reservation\">\n");
      out.write("                    <p class=\"korail_reservation_status status_cancel\">취소완료</p>\n");
      out.write("                    <p class=\"korail_reservation_number\">예약번호 <span>20220926138142</span></p>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"mypage_content_korail_info\">\n");
      out.write("                    <div class=\"info_train train\">\n");
      out.write("                      <div class=\"info_train_station\">\n");
      out.write("                        <p class=\"station\">용산</p>\n");
      out.write("                        <p class=\"time\">05:10</p>\n");
      out.write("                      </div>\n");
      out.write("                      <i class=\"fa-solid fa-arrow-right\"></i>\n");
      out.write("                      <div class=\"info_train_station\">\n");
      out.write("                        <p class=\"station\">광명</p>\n");
      out.write("                        <p class=\"time\">05:24</p>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">열차</p>\n");
      out.write("                      <p class=\"txt\">KTX</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">출발일</p>\n");
      out.write("                      <p class=\"txt\">2022년 12월 11일 (일)</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">인원</p>\n");
      out.write("                      <p class=\"txt\">성인1</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"info_train\">\n");
      out.write("                      <p class=\"tit\">좌석</p>\n");
      out.write("                      <p class=\"txt\">15호차 2B</p>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("            <div class=\"mypage_content_activity_none\">\n");
      out.write("              <img src=\"../images/myPage/reservation_noimg.svg\" alt=\"\" class=\"none_img\">\n");
      out.write("              <p class=\"none_tit\">탑승 예정인 열차 승차권이 없습니다</p>\n");
      out.write("              <p class=\"none_txt\">와그와 여행을 떠나보세요!</p>\n");
      out.write("              <a href=\"#n\" class=\"link\">열차 승차권 예매하기</a>\n");
      out.write("            </div>\n");
      out.write("          </article>\n");
      out.write("        </section>\n");
      out.write("      </main>\n");
      out.write("      <footer class=\"footer\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bottom.jsp", out, false);
      out.write("\n");
      out.write("      </footer>\n");
      out.write("    </div>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
