/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-01-15 16:51:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypageLeft_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<a href=\"mypageProfile.jsp\" class=\"mypage_profile\">\n");
      out.write("  <img src=\"../images/myPage/user_icon_def.png\" alt=\"\" class=\"img\">\n");
      out.write("  <span class=\"name\">김다은</span>\n");
      out.write("  <i class=\"fa-solid fa-chevron-right\"></i>\n");
      out.write("  <i class=\"fa-solid fa-chevron-right\"></i>\n");
      out.write("</a>\n");
      out.write("<ul class=\"mypage_list\">\n");
      out.write("  <li>\n");
      out.write("    <div href=\"#n\" class=\"link\">\n");
      out.write("      <i class=\"fa-solid fa-clipboard-list\"></i>\n");
      out.write("      <p class=\"title\">\n");
      out.write("        예약 및 구매내역\n");
      out.write("        <a href=\"mypageActivity.jsp\" class=\"goods_link\">액티비티</a>\n");
      out.write("        <a href=\"mypageHotel.jsp\" class=\"goods_link\">숙소</a>\n");
      out.write("        <a href=\"mypageKorail.jsp\" class=\"goods_link\">열차 승차권</a>\n");
      out.write("      </p>\n");
      out.write("    </div>\n");
      out.write("  </li>\n");
      out.write("  <li>\n");
      out.write("    <a href=\"mypageCoupon.jsp\" class=\"link\">\n");
      out.write("      <i class=\"fa-solid fa-ticket\"></i>\n");
      out.write("      <p class=\"title\">쿠폰 (<span>0</span>)</p>\n");
      out.write("    </a>\n");
      out.write("  </li>\n");
      out.write("  <li>\n");
      out.write("    <a href=\"mypageReview.jsp\" class=\"link\">\n");
      out.write("      <i class=\"fa-solid fa-comment-dots\"></i>\n");
      out.write("      <p class=\"title\">이용후기</p>\n");
      out.write("    </a>\n");
      out.write("  </li>\n");
      out.write("  <li>\n");
      out.write("    <a href=\"mypageBasket.jsp\" class=\"link\">\n");
      out.write("      <i class=\"fa-solid fa-basket-shopping\"></i>\n");
      out.write("      <p class=\"title\">장바구니</p>\n");
      out.write("    </a>\n");
      out.write("  </li>\n");
      out.write("  <li>\n");
      out.write("    <a href=\"mypageWishlist.jsp\" class=\"link\">\n");
      out.write("      <i class=\"fa-solid fa-heart\"></i>\n");
      out.write("      <p class=\"title\">위시리스트</p>\n");
      out.write("    </a>\n");
      out.write("  </li>\n");
      out.write("</ul>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
