/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-01-12 08:34:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class station_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <div class = \"korail_station_popup_box\">\r\n");
      out.write("    <div class = \"korail_station_popup_title\">\r\n");
      out.write("      <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi_search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z\"/>\r\n");
      out.write("      </svg>\r\n");
      out.write("      <input type=\"text\" placeholder=\"어디로 떠나시나요?\" class=\"korail_station_popup_title_input\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"korail_station_popup_content\">\r\n");
      out.write("      <div class=\"popular_station\">\r\n");
      out.write("        <div class=\"popular_station_title\">주요역</div>\r\n");
      out.write("        <div class=\"popular_station_name\">광주</div>\r\n");
      out.write("        <div class=\"popular_station_name\">대전</div>\r\n");
      out.write("        <div class=\"popular_station_name\">동대구</div>\r\n");
      out.write("        <div class=\"popular_station_name\">목포</div>\r\n");
      out.write("        <div class=\"popular_station_name\">부산</div>\r\n");
      out.write("        <div class=\"popular_station_name\">서대전</div>\r\n");
      out.write("        <div class=\"popular_station_name\">신경주</div>\r\n");
      out.write("        <div class=\"popular_station_name\">익산</div>\r\n");
      out.write("        <div class=\"popular_station_name\">용산</div>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"railWay_station\">\r\n");
      out.write("        <div class=\"railWay_station_title\">철도역</div>\r\n");
      out.write("        <div class=\"railWay_station_list\">\r\n");
      out.write("          <div class=\"consonants\">\r\n");
      out.write("            <ul class =\"consonants_ul\">\r\n");
      out.write("              <li class=\"consonants_list on\">ㄱ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㄴ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㄷ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㅁ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㅂ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㅅ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㅇ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㅈ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㅊ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㅌ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㅍ</li>\r\n");
      out.write("              <li class=\"consonants_list\">ㅎ</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class = \"railWay_station_name_box\">\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name disabled\">가평</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">강경</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">강경</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">강릉</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">개포</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">건천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">경산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">경주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">계룡</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">고한</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">곡성</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">공주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">광명</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">광양</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">광주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">광주송정</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">광천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">구래구</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">구미</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">구포</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">군북</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">군산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">극락강</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">기장</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">김제</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">김천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">김천구미</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">나주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">남성현</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">남원</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">남창</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">논산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">능주</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">다시</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">단양</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">대구</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">대야</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">대전</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">대천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">덕소</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">덕하</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">도계</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">도고온천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">동대구</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">동백산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">동해</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">둔내</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">독량</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">마산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">만종</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">매곡</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">명봉</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">목포</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">몽탄</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">무안</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">묵호</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">물금</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">민둥산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">밀양</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">반성</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">백양사</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">벌교</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">보성</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">봉화</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">부강</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">부산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">부전</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">북영천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">북천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">분천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">불국사</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">봉양</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">사복</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">사상</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">삼랑진</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">삼례</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">삼산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">삼탄</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">삼교</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">상동</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">상봉</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">상주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">서경주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">서광주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">서대전</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">서울</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">서정리</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">서천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">석불</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">석포</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">성환</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">센텀</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">수원</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">순천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">승부</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">신경주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">신기</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">신녕</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">신동</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">신례원</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">신탄진</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">신태인</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">신해운대</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">심천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">서원주</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">아산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">안강</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">안동</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">안양</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">약목</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">양원</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">양평</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">여수엑스포</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">여천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">연산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">영덕</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">영동</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">영등포</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">영월</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">영주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">영천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">예당</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">예미</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">예산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">예천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">오근장</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">오산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">오송</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">오수</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">옥산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">옥천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">온야온천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">완사</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">왜관</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">용궁</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">용문</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">용산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">울산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">웅천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">원동</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">원주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">월포</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">음성</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">의성</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">이양</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">이원</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">익산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">일로</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">일신</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">임기</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">임성리</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">임실</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">장사</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">장성</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">장항</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">전의</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">전주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">점촌</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">정동진</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">정읍</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">제천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">조성</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">조치원</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">좌천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">주덕</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">중리</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">증평</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">지탄</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">지평</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">진례</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">진부</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">진상</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">진영</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">진주</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">창원</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">창원중앙</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">천안</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">천안아산</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">청도</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">청량리</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">청리</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">청소</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">청주</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">청주공항</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">추풍령</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">춘앙</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">충주</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">탐리</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">태백</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">태화강</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">판교</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">평창</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">평택</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">포항</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">풍기</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"railWay_satation_name_ul\">  \r\n");
      out.write("              <li class=\"railWay_satation_name\">하동</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">하양</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">한림정</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">함안</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">함창</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">함평</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">행신</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">현동</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">호계</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">홍성</li>                            \r\n");
      out.write("              <li class=\"railWay_satation_name\">화명</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">화본</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">화순</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">황간</li>                              \r\n");
      out.write("              <li class=\"railWay_satation_name\">횡성</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">횡천</li>\r\n");
      out.write("              <li class=\"railWay_satation_name\">효천</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"no_search\">\r\n");
      out.write("      <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z\"/>\r\n");
      out.write("      </svg>\r\n");
      out.write("      <p>검색 결과가 없습니다.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
